In [82]:
include("../src/kernels/kernel.jl")

In [72]:
println(distancematrix(Gaussian(), [1, 2, 3] ,[3 4 5; 1 2 3]))

[0.0 24.0; 24.0 0.0]


The following code throws an error, because the array-type input for the length scale variable (second input) indicates that multiple length scales should be used. However, only one number is supplied.

In [73]:
distancematrix(Gaussian(), [2], [3 4 5; 1 2 3])


AssertionError: AssertionError: max(size(θ, 1), size(θ, 2)) == size(x, 2) == size(y, 2)

Instead, we should input [2] as a scalar 2, so that it's interpreted as a single length scale

In [74]:
distancematrix(Gaussian(), 2, [3 4 5; 1 2 3])

2×2 Array{Float64,2}:
  0.0  12.0
 12.0   0.0

In [83]:
cross_correlation(Gaussian(), 2, [1 2 3], [2 3 4])

1×1 Array{Float64,2}:
 0.049787068367863944

In [84]:
cross_correlation(Gaussian(), 2, [1; 2; 3], [2; 3; 4])

3×3 Array{Float64,2}:
 0.367879  0.0183156  0.00012341
 1.0       0.367879   0.0183156 
 0.367879  1.0        0.367879  

In [85]:
cross_correlation(Gaussian(), [1,2,3], [1; 2; 3], [2; 3; 4])

DimensionMismatch: DimensionMismatch("Incorrect vector dimensions.")

In [86]:
correlation(Gaussian(), 2, [1; 2; 3])

MethodError: MethodError: no method matching reshape(::Int64, ::Int64, ::Int64)
Closest candidates are:
  reshape(!Matched::AbstractArray, ::Int64...) at reshapedarray.jl:116
  reshape(!Matched::AbstractArray, ::Union{Int64, AbstractUnitRange}...) at reshapedarray.jl:110
  reshape(!Matched::AbstractArray, ::Union{Colon, Int64}...) at reshapedarray.jl:117