In [18]:
using Dates
using ArgParse
using Printf
using Random
using GaussianProcesses
using Cubature
include("../../btg.jl")

btgPredict

In [19]:
#########################
# initialize training set
#########################
# args here: ntrain, posc, yshift, are part of data process, no need to put into BTG options
# so keep them here 

df = DataFrame(CSV.File("../../datasets/abalone.csv", header = 0))
data = convert(Matrix, df[:,2:8]) #length, diameter, height, whole weight, shucked weight, viscera weight, shell weight
target = convert(Array, df[:, 9]) #age
ntrain_size = 1000
feature_size = 7
# shuffle data
randseed = 1234; rng = MersenneTwister(randseed)
ind_shuffle = randperm(rng, size(data, 1)) 
data = data[ind_shuffle, :]
target = target[ind_shuffle];
id_train = 1:100
n_train = length(id_train)
posx = 1:feature_size
x = data[id_train, posx]

posc = 3
posc = 1:posc
Fx = data[id_train, posc] 

y = float(target[id_train])
trainingData0 = trainingData(x, Fx, y) 
d = getDimension(trainingData0); n = getNumPts(trainingData0); p = getCovDimension(trainingData0)
ymax = trainingData0.ymax

22.0

In [24]:
rangeλ = reshape(convert(Array{Float64, 1}, [-1, 2]), 1, 2)
rangeθ = reshape(convert(Array{Float64, 1}, [100, 2000]), 1, 2)
rangeθm = repeat(rangeθ, 7, 1)

7×2 Array{Float64,2}:
 100.0  2000.0
 100.0  2000.0
 100.0  2000.0
 100.0  2000.0
 100.0  2000.0
 100.0  2000.0
 100.0  2000.0

In [29]:
options = Options(rangeθ, rangeλ, trainingData0, 1)

Options("BoxCox", "Gaussian", Dict("λ" => "Gaussian","θ" => "Gaussian"), Dict("Gaussian" => 12,"MonteCarlo" => 400), Dict("λ" => [-1.0 2.0],"θ" => [100.0 2000.0]), Dict{String,priorType}("λ" => Uniform(Real[-1.0 2.0], 1, Real[3.0]),"θ" => inverseUniform([100.0 2000.0], 1, Real[1900.0])), 1, 0.95)

In [30]:
options.parameter_range["λ"]

1×2 Array{Float64,2}:
 -1.0  2.0

In [31]:
options.parameter_range["θ"]

1×2 Array{Float64,2}:
 100.0  2000.0

In [32]:
@time btg0 = btg(trainingData0, options);

  2.444171 seconds (4.94 M allocations: 240.286 MiB, 4.30% gc time)


In [33]:
# @time model0 = btgModel(btg0);

In [34]:
##################################################
# process test data 
##################################################
ntrain_size = 800
id_test = (ntrain_size+1) :(3+ntrain_size)
n_test = length(id_test)
x_test = data[id_test, posx]; # n*d
posc = 1:3
Fx_test = data[id_test, posc] 
y_test_true = reshape(float(target[id_test]), 3, 1)

3×1 Array{Float64,2}:
 10.0
  7.0
 11.0

In [47]:
@time predict = btgPredict(x_test, Fx_test, btg0; y_true = y_test_true);

12×12 Array{Float64,2}:
 3.54944e-16  4.34664e-15  8.41411e-14  …  5.37718e-19  1.84734e-20
 9.57546e-8   1.08355e-6   1.66977e-5      4.85962e-15  8.55911e-17
 0.000505632  0.005001     0.0549122       1.59434e-16  1.43439e-18
 0.000260594  0.00216993   0.0166898       2.38741e-20  1.47063e-22
 4.88929e-6   3.49436e-5   0.000202844     5.10515e-24  2.63774e-26
 6.55111e-8   4.19123e-7   2.00731e-6   …  6.22002e-27  2.96262e-29
 1.4916e-9    8.85614e-9   3.74152e-8      3.74833e-29  1.71554e-31
 6.80989e-11  3.84605e-10  1.49669e-9      7.86005e-31  3.52226e-33
 5.98643e-12  3.26878e-11  1.20437e-10     4.27542e-32  1.89293e-34
 9.08628e-13  4.85105e-12  1.72396e-11     4.79554e-33  2.10792e-35
 2.05277e-13  1.0806e-12   3.75473e-12  …  9.01802e-34  3.94707e-36
 5.05663e-14  2.64235e-13  9.07451e-13     2.0221e-34   8.83142e-37


 weightsTensorGrid
  1.714573 seconds (7.36 M allocations: 293.506 MiB, 4.57% gc time)


In [48]:
predict.testingdata

testingData([0.675 0.51 … 0.3175 0.3965; 0.34 0.25 … 0.0405 0.05; 0.665 0.505 … 0.2925 0.32], [0.675 0.51 0.195; 0.34 0.25 0.075; 0.665 0.505 0.16], [10.0; 7.0; 11.0], 7, 3, 3)

In [49]:
predict.median

3-element Array{Real,1}:
 9.121171329404955
 6.816050410640659
 9.451162968569534

In [50]:
predict.credible_intervel

3-element Array{Array,1}:
 Real[4.8403041369058855, 18.96200130204881]
 Real[5.795380873543383, 8.105537406676829]
 Real[6.944307586036174, 13.094156687117545]

In [51]:
predict.absolute_error

3-element Array{Real,1}:
 0.8788286705950448
 0.18394958935934103
 1.548837031430466

In [52]:
predict.negative_log_pred_density

3-element Array{Real,1}:
 -0.8938289428414969
 -2.6529760490608183
 -1.1364793759317373

In [53]:
predict.time_cost

Dict{String,Float64} with 5 entries:
  "time_median"     => 8.75449
  "time_total"      => 53.2284
  "time_eval"       => 0.136463
  "time_preprocess" => 26.4767
  "time_CI"         => 16.8319